In [7]:
import pommerman
from pommerman import agents
import numpy as np
import time

In [2]:
# Create a set of agents (exactly four)
agent_list = [
    agents.SimpleAgent(),
    agents.SimpleAgent(),
    agents.SimpleAgent(),
    agents.SimpleAgent(),
    # agents.DockerAgent("pommerman/simple-agent", port=12345),
]

In [3]:
# Make the "Free-For-All" environment using the agent list
env = pommerman.make('PommeFFACompetition-v0', agent_list)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [35]:
rewards = []
lengths = []
start_time = time.time()
# Run the episodes just like OpenAI Gym
for i_episode in range(1000):
    state = env.reset()
    done = False
    lens = [None] * 4
    t = 0
    while not done:
        #env.render()
        actions = env.act(state)
        state, reward, done, info = env.step(actions)
        t += 1
        for j in range(4):
            if lens[j] is None and reward[j] != 0:
                lens[j] = t
    rewards.append(reward)
    lengths.append(lens)
    print('Episode {} finished'.format(i_episode))
elapsed = time.time() - start_time

Episode 0 finished
Episode 1 finished
Episode 2 finished
Episode 3 finished
Episode 4 finished
Episode 5 finished
Episode 6 finished
Episode 7 finished
Episode 8 finished
Episode 9 finished
Episode 10 finished
Episode 11 finished
Episode 12 finished
Episode 13 finished
Episode 14 finished
Episode 15 finished
Episode 16 finished
Episode 17 finished
Episode 18 finished
Episode 19 finished
Episode 20 finished
Episode 21 finished
Episode 22 finished
Episode 23 finished
Episode 24 finished
Episode 25 finished
Episode 26 finished
Episode 27 finished
Episode 28 finished
Episode 29 finished
Episode 30 finished
Episode 31 finished
Episode 32 finished
Episode 33 finished
Episode 34 finished
Episode 35 finished
Episode 36 finished
Episode 37 finished
Episode 38 finished
Episode 39 finished
Episode 40 finished
Episode 41 finished
Episode 42 finished
Episode 43 finished
Episode 44 finished
Episode 45 finished
Episode 46 finished
Episode 47 finished
Episode 48 finished
Episode 49 finished
Episode 50

Episode 396 finished
Episode 397 finished
Episode 398 finished
Episode 399 finished
Episode 400 finished
Episode 401 finished
Episode 402 finished
Episode 403 finished
Episode 404 finished
Episode 405 finished
Episode 406 finished
Episode 407 finished
Episode 408 finished
Episode 409 finished
Episode 410 finished
Episode 411 finished
Episode 412 finished
Episode 413 finished
Episode 414 finished
Episode 415 finished
Episode 416 finished
Episode 417 finished
Episode 418 finished
Episode 419 finished
Episode 420 finished
Episode 421 finished
Episode 422 finished
Episode 423 finished
Episode 424 finished
Episode 425 finished
Episode 426 finished
Episode 427 finished
Episode 428 finished
Episode 429 finished
Episode 430 finished
Episode 431 finished
Episode 432 finished
Episode 433 finished
Episode 434 finished
Episode 435 finished
Episode 436 finished
Episode 437 finished
Episode 438 finished
Episode 439 finished
Episode 440 finished
Episode 441 finished
Episode 442 finished
Episode 443 f

Episode 787 finished
Episode 788 finished
Episode 789 finished
Episode 790 finished
Episode 791 finished
Episode 792 finished
Episode 793 finished
Episode 794 finished
Episode 795 finished
Episode 796 finished
Episode 797 finished
Episode 798 finished
Episode 799 finished
Episode 800 finished
Episode 801 finished
Episode 802 finished
Episode 803 finished
Episode 804 finished
Episode 805 finished
Episode 806 finished
Episode 807 finished
Episode 808 finished
Episode 809 finished
Episode 810 finished
Episode 811 finished
Episode 812 finished
Episode 813 finished
Episode 814 finished
Episode 815 finished
Episode 816 finished
Episode 817 finished
Episode 818 finished
Episode 819 finished
Episode 820 finished
Episode 821 finished
Episode 822 finished
Episode 823 finished
Episode 824 finished
Episode 825 finished
Episode 826 finished
Episode 827 finished
Episode 828 finished
Episode 829 finished
Episode 830 finished
Episode 831 finished
Episode 832 finished
Episode 833 finished
Episode 834 f

In [36]:
np.mean(rewards, axis=0), np.std(rewards, axis=0)

(array([-0.494, -0.672, -0.606, -0.668]),
 array([0.8694619 , 0.74055115, 0.79546464, 0.74416127]))

In [37]:
np.mean(lengths, axis=0), np.std(lengths, axis=0)

(array([277.072, 240.809, 259.901, 253.54 ]),
 array([215.66555779, 222.48559171, 216.87881685, 235.05149308]))

In [38]:
np.mean(rewards), np.std(rewards)

(-0.61, 0.7924014134263012)

In [39]:
np.mean(lengths), np.std(lengths)

(257.8305, 223.03573653060624)

In [40]:
total_timesteps = np.sum(np.max(lengths, axis=1))
elapsed, total_timesteps, elapsed / total_timesteps

(2982.6670775413513, 1527648, 0.0019524570303769923)

In [41]:
np.savez_compressed("eval_simple_1000.npz", rewards=rewards, lengths=lengths, elapsed=elapsed, total_timesteps=total_timesteps)